### ISSUE TITLE
None and empty string input are not camelized correctly

### ISSUE THREAD

**Issue by lorrin** [nficano/humps#256]
`None` and empty string input are not camelized correctly.

**To Reproduce**
```
>>> import humps
>>> humps.camelize('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lorrin/Documents/Lorrin/Code/humps/lib/python3.10/site-packages/humps/main.py", line 62, in camelize
    s = s[0].lower() + s[1:]
IndexError: string index out of range
>>> humps.camelize(None)
'none'
```

**Expected behavior**
`camelize` of empty string should return empty string, not raise an error.

`camelize` of `None` should return `None` (or an empty string or raise an error), but not return `'none'`.

**Additional context**
pyhumps-3.5.3 on Python 3.10.2 on macOS 12.3.1 (21E258)

**Comment by lorrin** [comment]
`humps.decamelize('')` works, but `humps.decamelize(None)` also returns `'none'`
